build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job:
  stage: test
  script:
    - echo "Commit tag: $CI_COMMIT_TAG."
    - echo "Deploy token: $CI_PROJECT_ID."

deploy-prod:
  stage: deploy
  script:
    - curl -sS --show-error --fail --data tag=${CI_COMMIT_TAG} token=vladaurbanek-published "https://gitlab+deploy-token-1783388:${DEPLOY_TOKEN}@gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/composer"
  environment: production
