build-job:
  stage: build
  script:
    - curl -sS --show-error --fail --data tag=${CI_COMMIT_TAG} "https://gitlab+deploy-token-1783351:${DEPLOY_TOKEN}@gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/composer"
